export { default as Home } from './Home'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as Projects } from './Projects'
export { default as ProjectDetails } from './ProjectDetails'
export { default as OwnHouse } from './OwnHouse'
export { default as RentApartment } from './RentApartment'
export { default as Contact } from './Contact'